/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Local */

#ifndef _Included_Local
#define _Included_Local
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Local
 * Method:    send
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_Local_send
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
